version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pix_scheduler_db
    environment:
      POSTGRES_DB: pix_scheduler
      POSTGRES_USER: pix_user
      POSTGRES_PASSWORD: pix_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pix_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pix_scheduler_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pixscheduler.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - pix_network

volumes:
  postgres_data:

networks:
  pix_network:
    driver: bridge 


    